on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  dispatch:
    name: Dispatch event to k8s
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract tag as env var
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Notify k8s
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ctrl-hub/k8s
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: ${{ inputs.name }}
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "tag": "${{ env.RELEASE_VERSION }}"}'
