on:
  workflow_call:
    inputs:
      owner:
        required: true
        type: string
      project:
        required: true
        type: string
      image:
        required: true
        type: string
    secrets:
      DISPATCH_PAT:
        required: true

jobs:
  dispatch:
    name: Dispatch event to k8s
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract tag as env var
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DISPATCH_PAT }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'k8s',
              workflow_id: '.github/workflows/cd.yaml',
              ref: 'main',
              inputs: {
                owner: '${{ inputs.owner }}',
                project: '${{ inputs.project }}',
                image: '${{ inputs.image }}',
                ref: '${{ github.ref }}',
                sha: '${{ github.sha }}',
                tag: '${{ env.RELEASE_VERSION }}',
              },
            })
