on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  dispatch:
    name: Dispatch event to k8s
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract tag as env var
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'k8s',
              workflow_id: '71970969',
              ref: 'main',
              inputs: {
                name: '${{ inputs.name }}',
                ref: '${{ github.ref }}',
                sha: '${{ github.sha }}',
                tag: '${{ env.RELEASE_VERSION }}',
              },
            })
